[menu]
executable = "rofi"
args = [
  "-dmenu",
  "-markup",
  "-show-icons",
  "-no-case-sensitive",
  "-no-drun-use-desktop-cache",
  "-p",
  "{prompt}",
]

[format]
window_format = "{urgency_start}{title}{urgency_end} — {app_name} on workspace {workspace_name} \u0000icon\u001f{app_icon}"
workspace_format = "{name}"
urgency_start = '<span background="darkred" foreground="yellow">'
urgency_end = '</span>'
html_escape = false
icon_dirs = [
  "/usr/share/icons/hicolor/scalable/apps",
  "/usr/share/icons/hicolor/48x48/apps",
  "/usr/share/pixmaps",
]

[layout]
auto_tile = false
auto_tile_min_window_width_per_output_width = [
  [
    1024,
    500,
  ],
  [
    1280,
    600,
  ],
  [
    1400,
    680,
  ],
  [
    1440,
    700,
  ],
  [
    1600,
    780,
  ],
  [
    1920,
    920,
  ],
  [
    2560,
    1000,
  ],
  [
    3440,
    1000,
  ],
  [
    4096,
    1200,
  ],
]
