---
# https://taskfile.dev

version: '3'

env: {}

vars:
  to: '~'
  args: ''
  sudo: false
  verbosity: '{{ repeat (.LOG_LEVEL | default 1 | int) "v" }}'

tasks:
  plan:
    label: 'plan: {{ .to }} -> {{ .CLI_ARGS }}'
    desc: Plan to target.
    cmds:
      - stow --no-folding -n{{ .verbosity }}t {{ .to }} {{ .CLI_ARGS }}

  deploy:
    desc: Deploy to a target.
    label: 'deploy: {{ .to }} -> {{ .CLI_ARGS }}'
    cmds:
      # - task: plan
      #   vars:
      #     CLI_ARGS: '{{ .CLI_ARGS }}'
      #     to: '{{ .to }}'
      - '{{ if .sudo }}sudo {{ end }}stow {{ .args }} --no-folding -{{ .verbosity }}t {{ .to }} {{ .CLI_ARGS }}'
    status:
      - '{{ .status | default "false" }}'

  undeploy:
    label: 'undeploy: {{ .to }} -> {{ .CLI_ARGS }}'
    desc: Remove a stowed target.
    cmds:
      - stow {{ .args }} -{{ .verbosity }}t {{ .to }} -D {{ .CLI_ARGS }}
    status:
      - '{{ .status | default "false" }}'

  deploy:run:
    desc: Deploys to all targets
    deps:
      - task: deploy:linux
      - task: deploy:macos

  deploy:linux:
    desc: Deploy to target.
    platforms:
      - linux
    cmds:
      - task: deploy
        vars:
          to: '~'
          CLI_ARGS: avizo commitizen desktop file-manager-actions fonts foot gitconfig khal kitty mako mimetypes pacman pipewire rofi scripts shikane swappy sway swaync swayr swayimg sworkstyle swaylock waybar wireplumber waylogout wlogout xauthority xdg-desktop-portal xdg-desktop-portal-termfilechooser
          # args: --adopt
      # HACK: little trick to change the configuration for nvidia
      - task: deploy
        vars:
          to: '~'
          CLI_ARGS: chrome electron
          # status: '! [[ "$LIBVA_DRIVER_NAME" != "nvidia" ]]'
          status: test -d /usr/lib/nvidia
      - task: deploy
        vars:
          to: '~'
          CLI_ARGS: chrome-nvidia electron-nvidia
          # status: '! [[ "$LIBVA_DRIVER_NAME" == "nvidia" ]]'
          status: test ! -d /usr/lib/nvidia
      # HACK: little trick to change the configuration for nvidia
      - task: deploy
        vars:
          sudo: true
          to: '/'
          CLI_ARGS: rootfs
          args: --adopt

  deploy:macos:
    desc: Deploy to target.
    platforms:
      - darwin
    cmds:
      - stow --no-folding -{{ .verbosity }}t ~ chrome commitizen gitconfig yabai sketchybar janky-borders kitty

  deploy:gaming:
    desc: Deploy to target.
    platforms:
      - linux
    cmds:
      - task: deploy
        vars:
          to: '~'
          CLI_ARGS: mangohud steamtinkerlaunch
          args: --adopt
