---
# https://taskfile.dev

version: '3'

vars: {}

env: {}

tasks:
  deploy:
    desc: Deploy to target.
    cmds:
      - stow --no-folding -vvvt ~ avizo chrome commitizen file-manager-actions fonts foot gitconfig kanshi khal kitty mako pacman pipewire rofi sway swaync swayr sworkstyle vpn waybar wireplumber wlogout xauthority
      - sudo stow --adopt --no-folding -vvvt / rootfs

  plan:
    desc: Plan to target.
    cmds:
      - stow --no-folding -nvvvt ~ {{ .CLI_ARGS }}

  tui:
    desc: Run TUI.
    cmds:
      - stowtui
