---
# https://taskfile.dev

version: '3'

vars: {}

env: {}

tasks:
  deploy:
    desc: Deploy to target.
    cmds:
      - stow --no-folding -vvvt ~ avizo chrome commitizen electron desktop file-manager-actions fonts foot gitconfig kanshi khal kitty mako mimetypes pacman pipewire rofi sway swaync swayr sworkstyle vpn waybar wireplumber wlogout xauthority xdg-desktop-portal-termfilechooser
      - sudo stow --adopt --no-folding -vvvt / rootfs

  plan:
    desc: Plan to target.
    cmds:
      - stow --no-folding -nvvvt ~ {{ .CLI_ARGS }}
