[ids]
*

[main]
capslock = layer(control)
leftalt = layer(lower)
leftmeta+leftshift+f23 = layer(raise)

[lower]
q = !
w = @
e = #
r = $
t = %
y = ^
u = &
i = *
o = (
p = )
a = 1
s = 2
d = 3
f = 4
g = 5
h = 6
j = 7
k = 8
l = 9
; = 0
apostrophe = S-apostrophe
z = S-leftbrace
x = S-rightbrace
c = S-minus
v = S-equal
b = S-backslash
n = backslash
m = equal
, = minus
. = leftbrace
/ = rightbrace

[raise]
q = f1
w = f2
e = f3
r = f4
t = noop
y = noop
u = C-left
i = up
o = C-right
p = pageup
backspace = delete
a = f5
s = f6
d = f7
f = f8
g = noop
h = noop
j = left
k = down
l = right
; = pagedown
apostrophe = enter
z = f9
x = f10
c = f11
v = f12
b = noop
n = sysrq
m = home
, = noop
. = end
/ = noop
rightshift = noop

[lower+raise]
grave = noop
q = insert
w = scrolllock
e = noop
r = noop
t = noop
y = brightnessup
u = volumedown
i = mute
o = volumeup
p = noop
backspace = noop
a = noop
s = noop
d = noop
f = noop
g = noop
h = brightnessdown
j = previoussong
k = playpause
l = nextsong
; = noop
apostrophe = noop
z = noop
x = noop
c = noop
v = noop
b = noop
n = noop
m = noop
, = noop
. = noop
/ = noop
rightshift = noop
