[atEnd]
atEndAction=0
atEndLoopDelay=3

[background]
color=@Variant(\0\0\0\x43\x1\xff\xff\f\f\f\f\f\f\0\0)
image=@Variant(\0\0\0\x11\xff\xff\xff\xff)
opacity=1
shadows=false
transparency=true

[countdown]
autoStart=true
disappearWithin=1
enabled=true
frame=true
iterations=1

[editor]
forceQtTextRenderer=false

[files]
lastDocument=

[flip]
x=false
y=false

[keys]
decreaseVelocity=16777235
decreaseVelocityModifiers=0
fastForward=70
fastForwardModifiers=0
increaseVelocity=16777237
increaseVelocityModifiers=0
markerToggle=77
markerToggleModifiers=67108864
namedMarkerToggle=77
namedMarkerToggleModifiers=100663296
nextMarker=16777239
nextMarkerModifiers=67108864
pause=32
pauseModifiers=0
previousMarker=16777238
previousMarkerModifiers=67108864
reverse=73
reverseModifiers=0
rewind=82
rewindModifiers=0
setVelocity0=0
setVelocity0Modifiers=0
setVelocity1=49
setVelocity10=48
setVelocity10Modifiers=0
setVelocity1Modifiers=0
setVelocity2=50
setVelocity2Modifiers=0
setVelocity3=51
setVelocity3Modifiers=0
setVelocity4=52
setVelocity4Modifiers=0
setVelocity5=53
setVelocity5Modifiers=0
setVelocity6=54
setVelocity6Modifiers=0
setVelocity7=55
setVelocity7Modifiers=0
setVelocity8=56
setVelocity8Modifiers=0
setVelocity9=57
setVelocity9Modifiers=0
setVelocityModifier=134217728
skipBackwards=16777238
skipBackwardsModifiers=0
skipForward=16777239
skipForwardModifiers=0
stop=32
stopModifiers=67108864
toggle=16777272
toggleModifiers=0

[kirigamiUI]
hideFormattingToolsAlways=false
hideFormattingToolsWhilePrompting=true
onlyPositiveVelocity=true
showAnimationConfigOptions=false
showFontSpacingOptions=true

[mainWindow]
fakeFullScreen=false
height=1416
width=2560
x=700
y=0

[networkDialog]
autoReload=false
autoReloadHours=0
autoReloadMinutes=5
autoReloadSeconds=0
url=

[orientation]
orientation=0

[pointers]
arrowLineWidth=15
colorsEditing=
colorsPrompting=
colorsReady=
debug=false
imageLeftPath=
imageRightPath=
imageVerticalOffset=0
pointerKind=0
qmlLeftPath=
qmlRightPath=
sameAsLeftPointer=false
textFont=22
textLeftPointer=
textRightPointer=
textVerticalOffset=-0.05
tint=false

[projections]
enabled=false
scale=true

[prompter]
stepsDefault=3

[prompterPlacement]
offset_v2d0=0
width_v2d0=0.02

[readRegion]
disableOverlayContrast=true
enabled=false
linesInRegion=1
placement=0.5
state=1
styleState=7

[scroll]
invertArrowKeys=false
invertScrollDirection=false
noScroll=false
scrollAsDial=false
throttleWheel=true
wheelThrottleFactor=8

[telemetry]
enabled=false

[timer]
color=@Variant(\0\0\0\x43\x1\xff\xff\xaa\xaa\xaa\xaa\xaa\xaa\0\0)
enabled=true
eta=true
stopwatch=true

[ui]
language=
layout=0

[viewport.prompter]
baseAcceleration=100
baseSpeed=100
fontSize=100
fontWYSIWYGSizeSlider=120
letterSpacing=0
lineHeight=180
paragraphSpacingSlider=1.01
windowStaysOnTop=false
wordSpacing=24
