Net/ThemeName "Graphite-yellow-Dark-compact"
Net/IconThemeName "Tela-dracula-dark"
Gtk/CursorThemeName "Breeze_Light"
Gtk/CursorThemeSize 24
Gtk/FontName "Segoe UI 12"
Gtk/MonospaceFontName "ConsolasLG Nerd Font 16"
Net/EnableEventSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Xft/DPI 98304
