# vim:ft=hyprlang

### Recording Mode

bind = $mod, R, submap, 󰕧 Recording: (r/R) toggle/pause | (o) OBS | (z) zoom | (q) stop | ESC

submap = 󰕧 Recording: (r/R) toggle/pause | (o) OBS | (z) zoom | (q) stop | ESC

# Toggle recording (start/stop)
bind = , r, exec, $recorder toggle
bind = , r, submap, reset

# Pause/resume recording
bind = SHIFT, r, exec, $recorder pause
bind = SHIFT, r, submap, reset

# Open OBS window
bind = , o, exec, $recorder open
bind = , o, submap, reset

# Stop recording
bind = , q, exec, $recorder stop
bind = , q, submap, reset

# Toggle zoom
bind = , z, exec, hypr-zoom -easing=InOutCubic -interp=Linear -target 1.5
bind = , z, submap, reset

# Exit recording mode
bind = , escape, submap, reset

submap = reset
