--force-dark-mode
--enable-gpu-rasterization
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebUIDarkMode,WebRTCPipeWireCapturer,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,CanvasOopRasterization,PlatformHEVCDecoderSupport
# --disable-gpu-compositing
--enable-gpu-compositing
--ozone-platform-hint=auto
--ozone-platform=wayland
