--force-dark-mode
--enable-features=WaylandWindowDecorations,WebUIDarkMode,WebRTCPipeWireCapturer,WebRtcPipeWireCamera,AcceleratedVideoEncoder,AcceleratedVideoEncodeLinux,PlatformHEVCDecoderSupport
# --disable-gpu-compositing
--ozone-platform=wayland
