[Unit]
PartOf=graphical-session.target
After=graphical-session.target

[Service]
ExecStart=
# ExecStart=/bin/zsh -c '[ -r %h/.zshsecrets ] && . %h/.zshsecrets; exec %h/.local/bin/hyprpilot daemon --hidden'
ExecStart=/bin/zsh -c '[ -r %h/.zshsecrets ] && . %h/.zshsecrets; exec /usr/bin/hyprpilot daemon --hidden'

[Install]
WantedBy=
WantedBy=graphical-session.target
