[Service]
ExecStart=
# ExecStart=/bin/bash -c '[ -r %h/.zshsecrets ] && . %h/.zshsecrets; exec %h/.local/bin/hyprpilot daemon --hidden'
ExecStart=/bin/bash -c '[ -r %h/.zshsecrets ] && . %h/.zshsecrets; exec /usr/bin/hyprpilot daemon --hidden'
