# vim:ft=swayconfig

### Autostart Applications

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec_always sh -c 'uwsm finalize; systemctl --user restart --no-block swayidle.service swaync.service swayosd.service kanshi.service sworkstyle.service swayrd.service autotiling-rs.service sway-audio-idle-inhibit.service; systemctl --user start --no-block clipse.service wl-gammarelay-rs.service playerctl-waybar.service poweralertd.service input-remapper-autoload.service ydotool.service'
