#!/usr/bin/env sh

# remove apple crap
# removes apple music
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# skhd --restart-service || skhd --start-service
sketchybar --reload || brew services restart sketchybar

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
yabai -m signal --add event=display_changed action="sketchybar --trigger display_change"

# .. more yabai startup stuff# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config auto_balance on
# padding
# yabai -m config external_bar all:30:0
yabai -m config external_bar all:0:30
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 4
# focus
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
# window_origin_display [default|focused|cursor]
# Specify which display a newly created window should be managed in.
# default: The display in which the window is created (standard macOS behaviour).
# focused: The display that has focus when the window is created.
# cursor: The display that currently holds the mouse cursor.
yabai -m config window_origin_display cursor
# mouse
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
# border
yabai -m config window_border_width 2
yabai -m config window_border_hidpi off
yabai -m config window_border_radius -1.0
yabai -m config window_opacity_duration 0.005
yabai -m config window_animation_duration 0.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xffe5c07b
yabai -m config normal_window_border_color 0xff38404b
yabai -m config insert_feedback_color 0xffd19a66

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Preferences$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add label="raycast" app="^Raycast$" manage=off
yabai -m rule --add label="Bitwarden" app="^Bitwarden$" layer=above manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# signals
yabai -m signal --add event=space_changed action="~/.config/yabai/scripts/auto-destroy.sh"
# yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.95 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"

yabai -m signal --add event=window_destroyed action="~/.config/yabai/scripts/focus-under-cursor.sh"
yabai -m signal --add event=window_minimized action="~/.config/yabai/scripts/focus-under-cursor.sh"
yabai -m signal --add event=application_hidden action="~/.config/yabai/scripts/focus-under-cursor.sh"

echo "yabai configuration loaded..."
