#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
skhd --restart-service

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# .. more yabai startup stuff# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config window_placement second_child
# padding
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 4
# mouse
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config window_border_width 2
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_topmost off
# yabai -m config active_window_border_color 0xffeed5a8
# yabai -m config normal_window_border_color 0xff282c34
# yabai -m config insert_window_border_color 0xffe06c75

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Preferences$" manage=off
yabai -m rule --add app="^Shottr$" manage=off

# signals
yabai -m signal --add event=space_changed action="~/.config/yabai/scripts/auto-destroy.sh"

echo "yabai configuration loaded..."
