#!/usr/bin/env bash
#
# GTK / fontconfig configuration side-effects for the compositor session.
# Dispatcher pattern so future config concerns can slot in without
# spawning new script files.
#
# subcommands:
#   font <alias> <family-with-size>
#       install a fontconfig alias so CSS `font-family: <alias>`
#       resolves to <family>. Typical callers wire `monospace` to
#       $term-font and `sans-serif` to $gui-font.
#
# usage:
#   gtk-config.sh font monospace  "ConsolasLG Nerd Font 11"
#   gtk-config.sh font sans-serif "Segoe UI 11"

set -eu

_font() {
  local alias_name="${1:?usage: gtk-config.sh font <alias> <family>}"
  local font_spec="${2:?usage: gtk-config.sh font <alias> <family>}"

  # Strip a trailing numeric size component ("Foo Bar 11" -> "Foo Bar");
  # fontconfig aliases take family names, not Pango specs.
  local family
  family="$(echo "$font_spec" | sed -E 's/ [0-9]+(\.[0-9]+)?$//')"

  local conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fontconfig/conf.d"
  mkdir -p "$conf_dir"

  local target="$conf_dir/50-${alias_name}.conf"
  cat >"$target" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <!-- generated by gtk-config.sh font; alias ${alias_name} -> ${family} -->
  <alias>
    <family>${alias_name}</family>
    <prefer>
      <family>${family}</family>
    </prefer>
  </alias>
</fontconfig>
EOF

  # Refresh so the alias applies without waiting for a session restart.
  fc-cache -f >/dev/null 2>&1 || true
}

cmd="${1:?usage: gtk-config.sh <subcommand> [args]}"
shift

case "$cmd" in
font) _font "$@" ;;
*)
  echo "gtk-config.sh: unknown subcommand: $cmd" >&2
  exit 2
  ;;
esac
