#!/usr/bin/env bash
#
# GTK / fontconfig configuration side-effects for the compositor session.
# Dispatcher pattern so future config concerns can slot in without
# spawning new script files.
#
# subcommands:
#   font <alias> <family-with-size>
#       install a strong fontconfig generic-family override so CSS
#       `font-family: <alias>` resolves to <family>. Typical callers
#       wire `monospace` to $term-font and `sans-serif` to $gui-font.
#
# usage:
#   gtk-config.sh font monospace  "ConsolasLG Nerd Font 11"
#   gtk-config.sh font sans-serif "Segoe UI 11"
#   gtk-config.sh gtk4-theme "Graphite-yellow-Dark-compact"

set -eu

_font() {
  local alias_name="${1:?usage: gtk-config.sh font <alias> <family>}"
  local font_spec="${2:?usage: gtk-config.sh font <alias> <family>}"

  # Strip a trailing numeric size component ("Foo Bar 11" -> "Foo Bar");
  # fontconfig rules take family names, not Pango specs.
  local family
  family="$(echo "$font_spec" | sed -E 's/ [0-9]+(\.[0-9]+)?$//')"

  local conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fontconfig/conf.d"
  mkdir -p "$conf_dir"

  local target="$conf_dir/50-${alias_name}.conf"
  cat >"$target" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <!-- generated by gtk-config.sh font; generic ${alias_name} -> ${family} -->
  <match target="pattern">
    <test qual="any" name="family">
      <string>${alias_name}</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>${family}</string>
    </edit>
  </match>
</fontconfig>
EOF

  # Refresh so the alias applies without waiting for a session restart.
  if [ "${GTK_CONFIG_SKIP_FC_CACHE:-0}" != "1" ]; then
    fc-cache -f >/dev/null 2>&1 || true
  fi
}

_gtk4_theme() {
  local theme="${1:?usage: gtk-config.sh gtk4-theme <theme>}"

  gsettings set org.gnome.desktop.interface gtk-theme "$theme"

  local theme_root
  if [ -d "$HOME/.themes/${theme}" ]; then
    theme_root="$HOME/.themes/${theme}"
  elif [ -d "${XDG_DATA_HOME:-$HOME/.local/share}/themes/${theme}" ]; then
    theme_root="${XDG_DATA_HOME:-$HOME/.local/share}/themes/${theme}"
  else
    theme_root="/usr/share/themes/${theme}"
  fi

  local theme_dir="${theme_root}/gtk-4.0"
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0"
  mkdir -p "$config_dir"

  if [ -d "$theme_dir/assets" ]; then
    cp -rf --backup "$theme_dir/assets" "$config_dir"
  fi

  if [ -f "$theme_dir/gtk.css" ]; then
    cp -rf --backup "$theme_dir/gtk.css" "$config_dir"
  fi

  if [ -f "$theme_dir/gtk-dark.css" ]; then
    cp -rf --backup "$theme_dir/gtk-dark.css" "$config_dir"
  else
    rm -rf "$config_dir/gtk-dark.css"
  fi

  if [ -d "$theme_dir/icons" ]; then
    cp -rf --backup "$theme_dir/icons" "$config_dir"
  fi
}

cmd="${1:?usage: gtk-config.sh <subcommand> [args]}"
shift

case "$cmd" in
font) _font "$@" ;;
gtk4-theme) _gtk4_theme "$@" ;;
*)
  echo "gtk-config.sh: unknown subcommand: $cmd" >&2
  exit 2
  ;;
esac
