# vim:ft=hyprlang

layerrule {
    name = swaync-control-center
    match:namespace = swaync-control-center
    no_screen_share = on
}

layerrule {
    name = swaync-notification-window
    match:namespace = swaync-notification-window
    no_screen_share = on
}
