-- Autostart Applications

hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start waybar@hyprland.service")
end)

hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprland-session.service")
end)

hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
end)

hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user restart hyprpaper.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user restart hypridle.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user restart swaync.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user restart swayosd.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user restart kanshi.service")
end)

-- hl.on("hyprland.start", function()
--   hl.exec_cmd("systemctl --user start dex.service")
-- end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start clipse.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start wl-gammarelay-rs.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start playerctl-waybar.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start poweralertd.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start input-remapper-autoload.service")
end)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start ydotool.service")
end)
